language: objective-c
script:
  - xcodebuild -workspace RocketCast.xcworkspace -scheme RocketCast -sdk iphonesimulator
  - xcodebuild test -workspace RocketCast.xcworkspace -scheme RocketCastTests -sdk iphonesimulator
