language: objective-c
script:
  - xctool -workspace RocketCast.xcworkspace -scheme RocketCast -sdk iphonesimulator
  - xctool test -workspace RocketCast.xcworkspace -scheme RocketCastTests -sdk iphonesimulator
